### PR TITLE
#11 - Force make printValue a String

### PR DESCRIPTION
**Pull request by 7coil**
image

`message.channel.send(` always expects a String - This makes all values always a String.
Also returns "returned nothing" when `undefined` encountered.

Also shifted `node_modules` folder into `.gitignore` - Please run `npm i` to reinstall modules.

### CODE REVIEW

**Comment by 7coil** [comment]
Btw, this pull request refers to #11

**Comment by adrifcastr** [comment]
node_modules are needed for the hosting service. Will merge when readded

**Comment by 7coil** [comment]
Can you not run `npm i` before the bot starts up on heroku?

I'll figure out how heroku works when I get home

**Comment by adrifcastr** [comment]
It's not on heroku, it's on deploys.io & the disk usage is limited there so sadly the caching exceeds the disk limit

**Comment by 7coil** [comment]
Apparently deploys.io doesn't even exist anymore - are you sure?

**Comment by 7coil** [comment]
The website is just a goodbye page

**Comment by adrifcastr** [comment]
It's rebranded to dashflo.net by now

**Comment by 7coil** [comment]
https://dashflo.net/knowledgebase/111/

> When you start the bot from our panel, our system runs "npm install" before the bot starts to ensure all packages are installed.

If you're really sure then I'll add it back:
node_modules really should not be distributed like this because you might encounter native modules that will only work on Windows and not Linux

**Comment by adrifcastr** [comment]
Yeah I am sure, it indeed runs that, which then crashes the process bc it runs out of available disk space

**Comment by 7coil** [comment]
That's dumb of them - maybe you should look somewhere else in the future

I'll add it back as another pull request soon

**Comment by adrifcastr** [comment]
I know that it's dumb, but I haven't yet found another hoster that isn't overpriced, seeing as a bot needs minimal resources, and most VPS providers offer way to big plans.

Also you could join the server for easier communication, just sayin'

**Comment by 7coil** [comment]
That sounds like a~~n un~~reasonable idea. I'll do that

**Pull request closed without merging**
